### ISSUE TITLE
Automatic interception for Chromium and Firefox-Nightly

### ISSUE THREAD

**Issue by jneidel** [httptoolkit/feedback#20]
I only have Chromium and Firefox-Nightly installed on my system.

Chromium is not supported by "Fresh Chrome": `Error: chrome is not installed in your system.`
Firefox-Nightly is not supported by "Fresh Firefox": `Error: firefox is not installed in your system.`

**Comment by pimterry** [comment]
Oooh, interesting! I assumed that'd work, but I haven't properly tested it, I can totally believe it doesn't.

Under the hood, browser detection and launching uses https://github.com/james-proxy/james-browser-launcher. It looks like Chromium should be pretty easy to add, since there's built-in support there, but FF nightly will take more work. FF Developer edition should already be supported though, if that's any use to you.

I'll take a look at Chromium now and see if I can get that in later today anyway, should be quick.

**Comment by pimterry** [comment]
In fact, looking into Firefox nightly, it looks like it's just a tarball you extract yourself, right? That makes it hard to know what a typical nightly install looks like, so it'll all depend on how you've set it up on your system.

I assume you're using Linux? On Linux, the Firefox detection just looks for a process in your PATH called `firefox` that when called with `firefox --version` will exit 0 and print a version (`firefox-developer` also works).

If you put a `firefox` symlink into your PATH that points to the nightly binary, everything should start working immediately. Click the disabled FF button in the UI to make it try and refresh the browser config. Can you test that and let me know if it works for you?

**Comment by pimterry** [comment]
I've now got Chromium working nicely: ![screenshot from 2019-01-21 15-13-34](https://user-images.githubusercontent.com/1526883/51479710-51b73200-1d8f-11e9-88d1-3cdb19b354b5.png)

I've combined them both into a single Chrome launcher to keep things simple, so it's the same button. If you have both installed, it'll use Chrome (since I think that's the more popular choice), but if you only have Chromium installed that'll be used automatically instead.

The UI part will update automatically on the next app restart, so it'll be correctly detected there, and you'll be able to launch it automatically after I do the next [HTTP Toolkit server](https://github.com/httptoolkit/httptoolkit-server) release, keep on eye over here for 0.1.3: https://github.com/httptoolkit/httptoolkit-server/releases. I'm planning to put that out sometime later today.

Let me know about the above points for Firefox Nightly. For now I'm not going to do anything more there, but let me know if that doesn't work or if there's a standard way to detect & launch FF nightly that would work better.

**Comment by jneidel** [comment]
With the new version (`0.1.3`) chromium is being automatically detected!

I've installed FF Nightly from the AUR, which generates a `firefox-nightly` binary.
Symlinking `firefox` to `firefox-nightly` works as intended.

I think adding `firefox-nightly` to your Firefox detection should do the job.

**Comment by pimterry** [comment]
Ok, great to hear. I've now opened a PR to add proper support for detecting `firefox-nightly` as Firefox here: https://github.com/james-proxy/james-browser-launcher/pull/82. Once that's merged and pulled in, we should be all good.

Thanks for reporting this! It's great to be able to make browser detection a bit more sturdy around these cases :+1:
