### ISSUE TITLE
Request forwarded to a new host updated Host: header

### ISSUE THREAD

**Issue by robertcope** [httptoolkit/feedback#43]
I thought this tool would be useful for testing a new CDN; I've been looking for something that I can hand to business users or other folks that aren't super technical. I purchased the Pro version and setup a simple Mock rule to forward requests for _www.ni.com_ to the new CDN's CNAME, _www.ni.com.cdn.cloudflare.net_. That worked, sort of; the problem is that it also updates the HTTP request's Host header, which created a request that is broken.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Ok, I see, so you currently have cloudflare set up as a CDN on `www.ni.com.cdn.cloudflare.net`, but you haven't yet CNAME'd `www.ni.com` to point to that, is that right?

This is an interesting case. Most of the time you really do want to rewrite the host header, because for most redirects that's required. Most servers are expecting requests at their own hostname, not somebody else's. I see how that's not true for this case though.

For you right now, this isn't possible with HTTP Toolkit. Being able to customize the host header on forwarded requests would be useful for a couple of other cases too, so I will look at that, but it'll be at least a week or so until I have time to get to it, everything is quite hectic with the new release.

That would probably take the form of a dropdown under the 'Forward the request' option, to specify a host header behaviour: 'replace with target', 'don't touch', and later perhaps 'replace with a custom value' (defaulting to 'replace with target'. Would that solve your problem?

**Comment by robertcope** [comment]
Yup, you got it. Your solution is almost exactly what I was envisioning. I think both use cases are valuable. Thanks for taking the time to respond and good luck with the release!

**Comment by pimterry** [comment]
Hi @robertcope, you'll be happy to hear that you can now configure the host header behaviour: 

![Screenshot from 2019-10-03 21-25-13](https://user-images.githubusercontent.com/1526883/66157585-5d4c3f80-e624-11e9-8f60-00984fe8ac29.png)

You'll need to let the app update - open it and it'll update in the background, wait 30 seconds and restart, and it should appear. Enjoy!
