### ISSUE TITLE
Fatal error on start, app is crashed

### ISSUE THREAD

**Issue by userlond** [httptoolkit/feedback#50]
When app starts, I get an error and app exits.

My platform is Windows 7 64bit. My account has restricted access.

But app starts ok when I run it as admin.

Maybe, related to https://github.com/httptoolkit/feedback/issues/19

If app doesn't work with restricted user accounts, it should be mentioned elsewhere, I think.

![HTTPToolkit error screenshot](https://www.dropbox.com/s/rv2wm53utrx253m/screenshot%202019-11-21-48%20001.png?raw=1)

**Comment by pimterry** [comment]
It shouldn't in general, but is possie that something has snuck through the cracks. I get error reports for crashes like this, and here is says the underlying crash is:

> Error: RegOpenKeyEx failed - exit code: '5'

I think that's due to https://github.com/vweevers/win-detect-browsers which is used internally to detect the installed browsers on windows, and reads some registry keys in the process of doing so. It's possible that you don't have access to read those as a restricted user. I'll look into it and see if I can find a quick fix.

**Comment by pimterry** [comment]
This was caused by a bug in win-detect-browsers that's now been [fixed](https://github.com/vweevers/win-detect-browsers/pull/65). You shouldn't see this issue any more, and running HTTP Toolkit in a restricted Windows user account should work fine. Thanks for the report!
