### ISSUE TITLE
Windows does not install

### ISSUE THREAD

**Issue by SteveALee** [httptoolkit/feedback#70]
Install on WIndows 10.0.18363 Build 18363 64 bit fails with

![image](https://user-images.githubusercontent.com/618922/81697091-ae46d080-945c-11ea-92ef-10a003146778.png)

Happens twice.

---

**Comment by pimterry** [comment]
Hmm, I'm not sure what's happened there! This doesn't seem to be a general problem, as there's many other Windows users with the latest release installed successfully, so it must be either an intermittent issue or something specific to this machine.

The error suggests that your installed version of HTTP Toolkit is somehow corrupted. Just rerunning the installer probably won't fix that (it'll just try to update to the given version, which won't do anything). You can safely delete `C:\Users\steve\AppData\Local\httptoolkit` though, which might be sufficient. If you delete that, and then reinstall the app, does it now work for you?

If not, is there anything else unusual about your machine? Have you run out of disk space, or hit any other disk issues recently?

**Comment by SteveALee** [comment]
Thanks Tim. So I deleted that folder, downloaed the installer again from C:\Users\steve\AppData\Local\httptoolkit.

Sadly I get the same error after looking at the throbber for 61s :(

There's nothing Unusal about my PC that I know of. A few web dev tools. Loads of mem and disc etc. It a reasonable spec Lenovo X1 Carbon. Not running any proxies or dodgy stuff (that I know off)

The error doesn't say what the DLL is. The error seems to indicate it thinks the exe is a DLL!? 

It's years since I've done win32 dev, but I guess a could see if depends is still around. Though the error seems to be an installer error.

**Comment by SteveALee** [comment]
Ah, so I just rerun (without deleting) but from explorer rather than via the Firefox downloads UI and it worked - bizarre. Maybe Firefox is running in some sort of sandbox or extensions are getting in the way.

I'm leaving the issue open in case you want to explore it more.

**Comment by SteveALee** [comment]
PS -I like it!! more that the Network tab in F12 tools ;) Except perhaps timing info

**Comment by pimterry** [comment]
Ok, great! No idea what the issue was there, but glad that's sorted for you. I've downloaded with Firefox elsewhere and had no issues, very mysterious.

I'm going to close this for now anyway, as I'm not sure there's much I can do to investigate, and it seems it's just this one case. I'll keep an eye out for others though, and if anybody else does hit this & find this issue, then they can reply here and I'll investigate further (and maybe your solution of launching the app from outside firefox will help). For now I don't think there's much more I can easily do.

By the way, on timing info: it's not as in-depth as the Firefox tools, but there is some timing info (along with very detailed compression & caching info) in the Pro performance section: https://httptoolkit.tech/docs/reference/view-page#the-performance-card. Might be of interest! There's no browser-style waterfall view yet though. I'm open to one in future, it's just not very high up my list right now.
