### ISSUE TITLE
How large is a request?

### ISSUE THREAD

**Issue by conartist6** [httptoolkit/feedback#71]
I'm trying to use this software to debug issues with GET requests larger than a certain size causing errors. Unfortunately no software will tell me the total size of my get request. I was certain yours would, but it didn't.

**Comment by pimterry** [comment]
Hi @conartist6, can you tell me a little more about what's happening? Is it the URL that's very large, or are you sending a very large request body? Is HTTP Toolkit showing nothing at all, or just not all the information you were looking for?

**Comment by conartist6** [comment]
It's a large URL. No body.

**Comment by conartist6** [comment]
The toolkit does not show any information. Chrome doesn't show any information either a size listed somewhere would help, or I could compute the size if I could see the raw text of the request.

**Comment by pimterry** [comment]
HTTP Toolkit should show something for every single request received, even if they're unparseable or totally invalid in some way. If your request isn't appearing in HTTP Toolkit at all then it's likely that it's really not being sent.

If you're trying to send it from within Chrome, this might mean that the browser is refusing to send it at all. Can you tell me anything more about where this request is coming from, and how you're sending it?

As a quick demo, you can run `fetch("/?a=" + "b".repeat(100000))` (that's a ~100,000 character URL) in Chrome with HTTP Toolkit interception, and that request will show up in HTTP Toolkit no problem.

If you try a fetch for a 10 million character URL (10MB of URL) then that doesn't appear and instead it throws an error in Chrome, but that's because it's not actually sent anywhere at all. You can confirm that by watching the raw data with wireshark if you'd like - you can't see the raw requests since there'll be over HTTPS, but you can check that no TCP packets are sent to the proxy port at all when the fetch is run.

**Comment by conartist6** [comment]
Sorry, I spoke imprecisely. It shows the request. It shows the URL and each header value and the failed response. The problem is that I cannot access the raw data, I can only see the request after it's been split apart, decorated with UI, etc. I can't find what I need to know, which is how big the raw request -- including URL and all headers -- was. No tool will tell me.

**Comment by pimterry** [comment]
Ah, I see. No, you can't see the raw byte size of the full request, that's not normally useful. Sounds interesting though, why is it important for your case?

In the export section for a selected request, you can export as HTTP/1.1 to get the raw data equivalent to the original request. Is that useful? Like so: ![Screenshot from 2020-05-13 18-03-50](https://user-images.githubusercontent.com/1526883/81836796-42d82e00-9544-11ea-89d0-d9bfdd03478e.png)

You could copy that out and count the characters elsewhere if you'd like. That's not _guaranteed_ to be byte-by-byte identical to the original request, but it should be very close.

Otherwise, your only alternative will be wireshark I think. That can definitely give you the raw bytes, but if you're talking about HTTPS traffic you'll also need to play some complicated games to get decryption working properly.

**Comment by conartist6** [comment]
Yes, that would be exactly what I want. Well... I'd prefer byte for byte, or at least seeing the original byte count, but close is probably good enough. In this case I know some piece of infra is configured to reject requests above a particular size, but being in a large complex corporate environment I don't know what that is. My best guess right now is that its limit is 4kb. Because the limitation seems to be an exact size (i.e. not a timeout), I would know that I'd found the correct configuration if I knew the number that I expected to find.

**Comment by pimterry** [comment]
Ah ok, that makes sense. Give that a go, and do let me know if you have any trouble.

Given that, I'm going to close this ticket for now. I think that raw export data should work for most common cases like this, and when anybody does need lower-level byte-by-byte traffic examination then getting into the weeds with wireshark is going to be a better option.

**Comment by conartist6** [comment]
Of course I can't actually use it since it's a pro feature, but at least someone can.
