### ISSUE TITLE
Mock redirect to other URL does not work with localhost

### ISSUE THREAD

**Issue by tilmans** [httptoolkit/feedback#88]
I've set up a Mock interface to redirect calls to a local instance of Elasticsearch (http://localhost:9200). This ran into timeouts because a Chrome started from HTTPToolkit apparently can't resolve localhost.
To fix this I had to use the local machine name instead.

Unfortunately the UI was not very helpful, it simply shows a spinner on the request and times out at some point.
I think it would be best if the Mock config UI would warn against using localhost - or if localhost worked :)

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
Hmm, HTTP Toolkit should definitely be able to resolve localhost, that's very odd. I've just tested localhost redirection on a couple of different machines to check, and it seems to work fine there.

Can you export & share the rule that isn't working, and any error messages you can see? What OS are you using? Anything unusual about the network setup?

**Comment by tilmans** [comment]
Running Chrome Version 83.0.4103.116 on Mac OS 10.15.5. I'm trying to connect to http://localhost:9200 (a default elasticsearch) which works fine on Chrome without HTTP Toolkit

With Toolkit on http://localhost:9200 does not work, even without a Mock set up. 

![2020-07-17 at 22 16](https://user-images.githubusercontent.com/884017/87827673-a865d500-c87b-11ea-94a6-8b7ca1b6bfec.png)

What *does* work is using http://127.0.0.1:9200 ...

**Comment by pimterry** [comment]
It looks like there's something odd happening in your IPv6 configuration, or at least HTTP Toolkit's interactions with it.

When you enter `localhost`, HTTP Toolkit has to resolve it, deciding whether you meant `::1` for IPv6 or `127.0.0.1` for IPv4. To do that, it checks for localhost IPv6 support (do you have a network interface with the address `::1`) and checks that the target port (9200) is in use for IPv6. If so it sends the request there, if not it just uses IPv4. Most services are available on both, in which case it doesn't matter, but sometimes they're only available on one.

Here, it looks like your elasticsearch instance isn't available on port 9200 over IPv6, and nonetheless HTTP Toolkit thinks it should be, because you support IPv6 and that port is currently in use.

I've just tested with a fresh elasticsearch install (7.8.0) with default settings on Mac 10.14.6, and HTTP Toolkit can reach it in Chrome as `localhost:9200`, `[::1]:9200` and (with a redirect rule) as `example.com`.

A few questions, so I can dig into this a bit more:

* Can you share your elasticsearch network configuration settings? According to [their docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html) it should bind to IPv4 & IPv6 by default, but it could be configured to use just one via `network.host`. Is there anything else unusual about your configuration?
* If you browse to `[::1]:9200` in a non-HTTP Toolkit Chrome window, does that successfully reach your elasticsearch instance?
* If you run `lsof -nPi | grep -i listen`, what does it show? That should list all listening ports, including the specific interface ip & address family that's in use in each case.

**Comment by tilmans** [comment]
Hi, thanks for detailed response.
You are right, it's an issue with the local ipv6 connection. ES is binding to ::1 as expected:

    publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}

But then doing a `curl [::1]:9200` does not return anything. Turns out this is an issue with the VPN I am using, as soon as I turn it off things work.

Issue fixed - only thing that would be nice is to add a background check in the UI when adding a redirect address. That will avoid stupid support emails :)

Cheers,
Tilman
