### ISSUE TITLE
Errror encountered

### ISSUE THREAD

**Issue by anuragagarwal32** [httptoolkit/feedback#93]
Following Error is encountered while using the toolkit:

"Server Crashed with 'TypeError: Cannot read property 'finishWrite' of null' (1)."

After the above error whenever I am trying to open HTTP Toolkit the below error is encountered:

"Server Crashed with 'Error: listen EADDRINUSE: address already in use 127.0.0.1:45457' (1)."

Kindly resolve this error.

---

_Does this affect you too? Click the +:smiley: icon in the top right and add a :+1: on issues to help decide where HTTP Toolkit goes next, or [go take a look & vote on the most popular ideas so far](https://github.com/httptoolkit/feedback/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc)._

**Comment by pimterry** [comment]
The proxy within the app must still be running, which is blocking that port. You can fix this by killing the process - look for a `node` process on your machine and stop it. Alternatively you can just restart your computer.

Once that's done the app will start again successfully.

The original `finishWrite` crash is a bug that was briefly live yesterday, and is now fixed. Once you successfully start the app it will update in the background, and then you won't see this issue again in future.

**Comment by pimterry** [comment]
This is now resolved, so I'm going to close it.

In the short term this error could still appear for some users who updated to this version while the bug was present, but their app will update in the background when opened, so nobody should ever see this more than once.

Thanks for reporting this issue @anuragagarwal32! Do let me know if you have any other trouble.
